### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by fizzvr** [edwinspire/uhttp#2]
error: al escuchar en otro path diferente al *uhttproot:

![sin nombre](https://f.cloud.github.com/assets/3093846/920184/34fb3d90-fed8-11e2-80e1-c7ef84810ee5.jpg)

path de programa: \Node\win
path de mi carpeta de salida: \Node\vr-web/final
en el archivo: Root=./vr-web/final

/\/\ la barras x.x

**Comment by edwinspire** [comment]
Poner el path absoluto (completo)
